// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	albumProto "github.com/go-park-mail-ru/2022_1_Wave/internal/microservices/album/albumProto"

	mock "github.com/stretchr/testify/mock"
)

// AlbumAgent is an autogenerated mock type for the AlbumAgent type
type AlbumAgent struct {
	mock.Mock
}

// AddToFavorites provides a mock function with given fields: userId, albumId
func (_m *AlbumAgent) AddToFavorites(userId int64, albumId int64) error {
	ret := _m.Called(userId, albumId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(userId, albumId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: _a0
func (_m *AlbumAgent) Create(_a0 *albumProto.Album) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*albumProto.Album) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateCover provides a mock function with given fields: _a0
func (_m *AlbumAgent) CreateCover(_a0 *albumProto.AlbumCover) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*albumProto.AlbumCover) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: _a0
func (_m *AlbumAgent) Delete(_a0 int64) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCover provides a mock function with given fields: _a0
func (_m *AlbumAgent) DeleteCover(_a0 int64) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAlbumsFromArtist provides a mock function with given fields: _a0
func (_m *AlbumAgent) GetAlbumsFromArtist(_a0 int64) ([]*albumProto.Album, error) {
	ret := _m.Called(_a0)

	var r0 []*albumProto.Album
	if rf, ok := ret.Get(0).(func(int64) []*albumProto.Album); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*albumProto.Album)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *AlbumAgent) GetAll() ([]*albumProto.Album, error) {
	ret := _m.Called()

	var r0 []*albumProto.Album
	if rf, ok := ret.Get(0).(func() []*albumProto.Album); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*albumProto.Album)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCovers provides a mock function with given fields:
func (_m *AlbumAgent) GetAllCovers() ([]*albumProto.AlbumCover, error) {
	ret := _m.Called()

	var r0 []*albumProto.AlbumCover
	if rf, ok := ret.Get(0).(func() []*albumProto.AlbumCover); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*albumProto.AlbumCover)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: _a0
func (_m *AlbumAgent) GetById(_a0 int64) (*albumProto.Album, error) {
	ret := _m.Called(_a0)

	var r0 *albumProto.Album
	if rf, ok := ret.Get(0).(func(int64) *albumProto.Album); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*albumProto.Album)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCoverById provides a mock function with given fields: _a0
func (_m *AlbumAgent) GetCoverById(_a0 int64) (*albumProto.AlbumCover, error) {
	ret := _m.Called(_a0)

	var r0 *albumProto.AlbumCover
	if rf, ok := ret.Get(0).(func(int64) *albumProto.AlbumCover); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*albumProto.AlbumCover)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFavorites provides a mock function with given fields: userId
func (_m *AlbumAgent) GetFavorites(userId int64) ([]*albumProto.Album, error) {
	ret := _m.Called(userId)

	var r0 []*albumProto.Album
	if rf, ok := ret.Get(0).(func(int64) []*albumProto.Album); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*albumProto.Album)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastCoverId provides a mock function with given fields:
func (_m *AlbumAgent) GetLastCoverId() (int64, error) {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastId provides a mock function with given fields:
func (_m *AlbumAgent) GetLastId() (int64, error) {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPopular provides a mock function with given fields:
func (_m *AlbumAgent) GetPopular() ([]*albumProto.Album, error) {
	ret := _m.Called()

	var r0 []*albumProto.Album
	if rf, ok := ret.Get(0).(func() []*albumProto.Album); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*albumProto.Album)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSize provides a mock function with given fields:
func (_m *AlbumAgent) GetSize() (int64, error) {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveFromFavorites provides a mock function with given fields: userId, albumId
func (_m *AlbumAgent) RemoveFromFavorites(userId int64, albumId int64) error {
	ret := _m.Called(userId, albumId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(userId, albumId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchByTitle provides a mock function with given fields: title
func (_m *AlbumAgent) SearchByTitle(title string) ([]*albumProto.Album, error) {
	ret := _m.Called(title)

	var r0 []*albumProto.Album
	if rf, ok := ret.Get(0).(func(string) []*albumProto.Album); ok {
		r0 = rf(title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*albumProto.Album)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *AlbumAgent) Update(_a0 *albumProto.Album) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*albumProto.Album) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCover provides a mock function with given fields: _a0
func (_m *AlbumAgent) UpdateCover(_a0 *albumProto.AlbumCover) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*albumProto.AlbumCover) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
