// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	trackProto "github.com/go-park-mail-ru/2022_1_Wave/internal/microservices/track/trackProto"
	mock "github.com/stretchr/testify/mock"
)

// TrackAgent is an autogenerated mock type for the TrackAgent type
type TrackAgent struct {
	mock.Mock
}

// AddToFavorites provides a mock function with given fields: userId, trackId
func (_m *TrackAgent) AddToFavorites(userId int64, trackId int64) error {
	ret := _m.Called(userId, trackId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(userId, trackId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: _a0
func (_m *TrackAgent) Create(_a0 *trackProto.Track) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*trackProto.Track) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: _a0
func (_m *TrackAgent) Delete(_a0 int64) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *TrackAgent) GetAll() ([]*trackProto.Track, error) {
	ret := _m.Called()

	var r0 []*trackProto.Track
	if rf, ok := ret.Get(0).(func() []*trackProto.Track); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: _a0
func (_m *TrackAgent) GetById(_a0 int64) (*trackProto.Track, error) {
	ret := _m.Called(_a0)

	var r0 *trackProto.Track
	if rf, ok := ret.Get(0).(func(int64) *trackProto.Track); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFavorites provides a mock function with given fields: _a0
func (_m *TrackAgent) GetFavorites(_a0 int64) ([]*trackProto.Track, error) {
	ret := _m.Called(_a0)

	var r0 []*trackProto.Track
	if rf, ok := ret.Get(0).(func(int64) []*trackProto.Track); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastId provides a mock function with given fields:
func (_m *TrackAgent) GetLastId() (int64, error) {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPopular provides a mock function with given fields:
func (_m *TrackAgent) GetPopular() ([]*trackProto.Track, error) {
	ret := _m.Called()

	var r0 []*trackProto.Track
	if rf, ok := ret.Get(0).(func() []*trackProto.Track); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPopularTracksFromArtist provides a mock function with given fields: _a0
func (_m *TrackAgent) GetPopularTracksFromArtist(_a0 int64) ([]*trackProto.Track, error) {
	ret := _m.Called(_a0)

	var r0 []*trackProto.Track
	if rf, ok := ret.Get(0).(func(int64) []*trackProto.Track); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSize provides a mock function with given fields:
func (_m *TrackAgent) GetSize() (int64, error) {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTracksFromAlbum provides a mock function with given fields: _a0
func (_m *TrackAgent) GetTracksFromAlbum(_a0 int64) ([]*trackProto.Track, error) {
	ret := _m.Called(_a0)

	var r0 []*trackProto.Track
	if rf, ok := ret.Get(0).(func(int64) []*trackProto.Track); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Like provides a mock function with given fields: _a0
func (_m *TrackAgent) Like(_a0 int64) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Listen provides a mock function with given fields: _a0
func (_m *TrackAgent) Listen(_a0 int64) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveFromFavorites provides a mock function with given fields: userId, artistId
func (_m *TrackAgent) RemoveFromFavorites(userId int64, artistId int64) error {
	ret := _m.Called(userId, artistId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(userId, artistId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchByTitle provides a mock function with given fields: title
func (_m *TrackAgent) SearchByTitle(title string) ([]*trackProto.Track, error) {
	ret := _m.Called(title)

	var r0 []*trackProto.Track
	if rf, ok := ret.Get(0).(func(string) []*trackProto.Track); ok {
		r0 = rf(title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *TrackAgent) Update(_a0 *trackProto.Track) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*trackProto.Track) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
