// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	trackProto "github.com/go-park-mail-ru/2022_1_Wave/internal/microservices/track/trackProto"
	mock "github.com/stretchr/testify/mock"
)

// TrackRepo is an autogenerated mock type for the TrackRepo type
type TrackRepo struct {
	mock.Mock
}

// AddToFavorites provides a mock function with given fields: id, userId
func (_m *TrackRepo) AddToFavorites(id int64, userId int64) error {
	ret := _m.Called(id, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(id, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: _a0
func (_m *TrackRepo) Create(_a0 *trackProto.Track) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*trackProto.Track) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: _a0
func (_m *TrackRepo) Delete(_a0 int64) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *TrackRepo) GetAll() ([]*trackProto.Track, error) {
	ret := _m.Called()

	var r0 []*trackProto.Track
	if rf, ok := ret.Get(0).(func() []*trackProto.Track); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFavorites provides a mock function with given fields: userId
func (_m *TrackRepo) GetFavorites(userId int64) ([]*trackProto.Track, error) {
	ret := _m.Called(userId)

	var r0 []*trackProto.Track
	if rf, ok := ret.Get(0).(func(int64) []*trackProto.Track); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastId provides a mock function with given fields:
func (_m *TrackRepo) GetLastId() (int64, error) {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPopular provides a mock function with given fields:
func (_m *TrackRepo) GetPopular() ([]*trackProto.Track, error) {
	ret := _m.Called()

	var r0 []*trackProto.Track
	if rf, ok := ret.Get(0).(func() []*trackProto.Track); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPopularTracksFromArtist provides a mock function with given fields: artistId
func (_m *TrackRepo) GetPopularTracksFromArtist(artistId int64) ([]*trackProto.Track, error) {
	ret := _m.Called(artistId)

	var r0 []*trackProto.Track
	if rf, ok := ret.Get(0).(func(int64) []*trackProto.Track); ok {
		r0 = rf(artistId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(artistId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSize provides a mock function with given fields:
func (_m *TrackRepo) GetSize() (int64, error) {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTracksFromAlbum provides a mock function with given fields: albumId
func (_m *TrackRepo) GetTracksFromAlbum(albumId int64) ([]*trackProto.Track, error) {
	ret := _m.Called(albumId)

	var r0 []*trackProto.Track
	if rf, ok := ret.Get(0).(func(int64) []*trackProto.Track); ok {
		r0 = rf(albumId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(albumId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Like provides a mock function with given fields: id, userId
func (_m *TrackRepo) Like(id int64, userId int64) error {
	ret := _m.Called(id, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(id, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Listen provides a mock function with given fields: id
func (_m *TrackRepo) Listen(id int64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveFromFavorites provides a mock function with given fields: trackId, userId
func (_m *TrackRepo) RemoveFromFavorites(trackId int64, userId int64) error {
	ret := _m.Called(trackId, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(trackId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchByTitle provides a mock function with given fields: title
func (_m *TrackRepo) SearchByTitle(title string) ([]*trackProto.Track, error) {
	ret := _m.Called(title)

	var r0 []*trackProto.Track
	if rf, ok := ret.Get(0).(func(string) []*trackProto.Track); ok {
		r0 = rf(title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SelectByID provides a mock function with given fields: _a0
func (_m *TrackRepo) SelectByID(_a0 int64) (*trackProto.Track, error) {
	ret := _m.Called(_a0)

	var r0 *trackProto.Track
	if rf, ok := ret.Get(0).(func(int64) *trackProto.Track); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*trackProto.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *TrackRepo) Update(_a0 *trackProto.Track) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*trackProto.Track) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
