version: "3.5"

volumes:
  postgres_data: { }
  mongo_data: { }

services:
  db:
    image: mausved/wave_postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=music
      - POSTGRES_DB=wave
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wave
      - MONGO_INITDB_ROOT_PASSWORD=music
      - MONGO_INITDB_DATABASE=urls
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
