FROM prom/prometheus
COPY metrics/prometheus /etc/prometheus
#CMD '--config.file=/etc/prometheus/prometheus.yml \
#    --storage.tsdb.path=/prometheus \
#    --web.console.libraries=/etc/prometheus/console_libraries \
#    --web.console.templates=/etc/prometheus/consoles \
#    --storage.tsdb.retention.time=200h \
#    --web.enable-lifecycle \
#    --web.external-url=/monitoring/prometheus/ \
#    --web.route-prefix=/monitoring/prometheus/ '

RUN #'--config.file=/etc/prometheus/prometheus.yml'
RUN #'--storage.tsdb.path=/prometheus'
RUN #'--web.console.libraries=/etc/prometheus/console_libraries'
RUN #'--web.console.templates=/etc/prometheus/consoles'
RUN #'--storage.tsdb.retention.time=200h'
RUN #'--web.enable-lifecycle'
RUN #'--web.external-url=/monitoring/prometheus/'
RUN #'--web.route-prefix=/monitoring/prometheus/'
