apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: caddy
  name: caddy
spec:
  ports:
    - name: "9093"
      port: 9093
      targetPort: 9093
    - name: "9091"
      port: 9091
      targetPort: 9091
    - name: "9121"
      port: 9121
      targetPort: 9121
    - name: "3000"
      port: 3000
      targetPort: 3000
    - name: "9090"
      port: 9090
      targetPort: 9090
    - name: "9113"
      port: 9113
      targetPort: 9113
  selector:
    io.kompose.service: caddy
status:
  loadBalancer: { }
