apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: artist
  name: artist
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: artist
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: artist
    spec:
      containers:
        - name: artist
          image: mausved/wave_artist
          ports:
            - containerPort: 8082
            - containerPort: 9082
          env:
            - name: DATABASE_CONNECTION
              value: user=postgres password=music dbname=wave host=db port=5432 sslmode=disable
            - name: dbType
              value: postgres
            - name: exporterPort
              value: :9082
            - name: port
              value: :8082
      restartPolicy: Always
      imagePullSecrets:
        - name: wave

status: { }
