// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: linker/linkerProto/linker.proto

package linkerProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HashWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash" example:"qweasdzX" db:"hash" validate:"nonnil"` // @gotags: json:"hash" example:"qweasdzX" db:"hash" validate:"nonnil"
}

func (x *HashWrapper) Reset() {
	*x = HashWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linker_linkerProto_linker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashWrapper) ProtoMessage() {}

func (x *HashWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_linker_linkerProto_linker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashWrapper.ProtoReflect.Descriptor instead.
func (*HashWrapper) Descriptor() ([]byte, []int) {
	return file_linker_linkerProto_linker_proto_rawDescGZIP(), []int{0}
}

func (x *HashWrapper) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type UrlWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url" example:"wave-music.online/api/v1/playlists/1" db:"url" validate:"nonnil"` // @gotags: json:"url" example:"wave-music.online/api/v1/playlists/1" db:"url" validate:"nonnil"
}

func (x *UrlWrapper) Reset() {
	*x = UrlWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linker_linkerProto_linker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UrlWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlWrapper) ProtoMessage() {}

func (x *UrlWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_linker_linkerProto_linker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlWrapper.ProtoReflect.Descriptor instead.
func (*UrlWrapper) Descriptor() ([]byte, []int) {
	return file_linker_linkerProto_linker_proto_rawDescGZIP(), []int{1}
}

func (x *UrlWrapper) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type UrlAndHashWrapper struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url  string `protobuf:"bytes,1,opt,name=url,proto3" json:"url" example:"buy.dog/pug" db:"url" validate:"nonnil"` // @gotags: json:"url" example:"buy.dog/pug" db:"url" validate:"nonnil"
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash" example:"qweasdzX" db:"hash" validate:"nonnil"` // @gotags: json:"hash" example:"qweasdzX" db:"hash" validate:"nonnil"
}

func (x *UrlAndHashWrapper) Reset() {
	*x = UrlAndHashWrapper{}
	if protoimpl.UnsafeEnabled {
		mi := &file_linker_linkerProto_linker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UrlAndHashWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlAndHashWrapper) ProtoMessage() {}

func (x *UrlAndHashWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_linker_linkerProto_linker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlAndHashWrapper.ProtoReflect.Descriptor instead.
func (*UrlAndHashWrapper) Descriptor() ([]byte, []int) {
	return file_linker_linkerProto_linker_proto_rawDescGZIP(), []int{2}
}

func (x *UrlAndHashWrapper) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UrlAndHashWrapper) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

var File_linker_linkerProto_linker_proto protoreflect.FileDescriptor

var file_linker_linkerProto_linker_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x22, 0x21, 0x0a, 0x0b, 0x48, 0x61, 0x73,
	0x68, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x1e, 0x0a, 0x0a,
	0x55, 0x72, 0x6c, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x39, 0x0a, 0x11,
	0x55, 0x72, 0x6c, 0x41, 0x6e, 0x64, 0x48, 0x61, 0x73, 0x68, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x32, 0x76, 0x0a, 0x0d, 0x4c, 0x69, 0x6e, 0x6b, 0x65,
	0x72, 0x55, 0x73, 0x65, 0x43, 0x61, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12,
	0x12, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2e, 0x55, 0x72, 0x6c, 0x57, 0x72, 0x61, 0x70,
	0x70, 0x65, 0x72, 0x1a, 0x13, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x73,
	0x68, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x12, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2e, 0x55, 0x72,
	0x6c, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x1a, 0x13, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x65,
	0x72, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x22, 0x00, 0x42,
	0x52, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f,
	0x2d, 0x70, 0x61, 0x72, 0x6b, 0x2d, 0x6d, 0x61, 0x69, 0x6c, 0x2d, 0x72, 0x75, 0x2f, 0x32, 0x30,
	0x32, 0x32, 0x5f, 0x31, 0x5f, 0x57, 0x61, 0x76, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_linker_linkerProto_linker_proto_rawDescOnce sync.Once
	file_linker_linkerProto_linker_proto_rawDescData = file_linker_linkerProto_linker_proto_rawDesc
)

func file_linker_linkerProto_linker_proto_rawDescGZIP() []byte {
	file_linker_linkerProto_linker_proto_rawDescOnce.Do(func() {
		file_linker_linkerProto_linker_proto_rawDescData = protoimpl.X.CompressGZIP(file_linker_linkerProto_linker_proto_rawDescData)
	})
	return file_linker_linkerProto_linker_proto_rawDescData
}

var file_linker_linkerProto_linker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_linker_linkerProto_linker_proto_goTypes = []interface{}{
	(*HashWrapper)(nil),       // 0: linker.HashWrapper
	(*UrlWrapper)(nil),        // 1: linker.UrlWrapper
	(*UrlAndHashWrapper)(nil), // 2: linker.UrlAndHashWrapper
}
var file_linker_linkerProto_linker_proto_depIdxs = []int32{
	1, // 0: linker.LinkerUseCase.Get:input_type -> linker.UrlWrapper
	1, // 1: linker.LinkerUseCase.Create:input_type -> linker.UrlWrapper
	0, // 2: linker.LinkerUseCase.Get:output_type -> linker.HashWrapper
	0, // 3: linker.LinkerUseCase.Create:output_type -> linker.HashWrapper
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_linker_linkerProto_linker_proto_init() }
func file_linker_linkerProto_linker_proto_init() {
	if File_linker_linkerProto_linker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_linker_linkerProto_linker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linker_linkerProto_linker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UrlWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_linker_linkerProto_linker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UrlAndHashWrapper); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_linker_linkerProto_linker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_linker_linkerProto_linker_proto_goTypes,
		DependencyIndexes: file_linker_linkerProto_linker_proto_depIdxs,
		MessageInfos:      file_linker_linkerProto_linker_proto_msgTypes,
	}.Build()
	File_linker_linkerProto_linker_proto = out.File
	file_linker_linkerProto_linker_proto_rawDesc = nil
	file_linker_linkerProto_linker_proto_goTypes = nil
	file_linker_linkerProto_linker_proto_depIdxs = nil
}
