apiVersion: v1
kind: Service
metadata:
  name: godeploy
spec:
  type: LoadBalancer
  selector:
    app: godeploy
  ports:
    - protocol: TCP
      name: "balancer-https"
      port: 443
      targetPort: "https"
    - protocol: TCP
      name: "balancer-http"
      port: 80
      targetPort: "http"
