apiVersion: v1
kind: Service
metadata:
  name: godeploy
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubectl.kubernetes.io/proxy-read-timeout: "1000s"
    kubectl.kubernetes.io/proxy-connect-timeout: "1000s"
    nginx.org/proxy-read-timeout: "1000s"
    nginx.org/proxy-connect-timeout: "1000s"
    nginx.org/websocket-services: "1"
spec:
  type: LoadBalancer
  selector:
    app: godeploy
  ports:
    - protocol: TCP
      name: "balancer-https"
      port: 443
      targetPort: "https"
    - protocol: TCP
      name: "balancer-http"
      port: 80
      targetPort: "http"
