apiVersion: apps/v1
kind: Deployment
metadata:
  name: godeploy
  labels:
    app: godeploy
spec:
  selector:
    matchLabels:
      app: godeploy
  template:
    metadata:
      labels:
        app: godeploy
    spec:
      containers:
        - name: godeploy
          image: mausved/wave_web
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: wave