apiVersion: v1
kind: Service
metadata:
  name: godeploy
  labels:
    k8s-app: nginx-backend
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    k8s-app: nginx-backend
  ports:
    - port: 80
      name: http
      targetPort: http
    - port: 443
      name: https
      targetPort: httpn
