apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
    - name: "9085"
      port: 9085
      targetPort: 9085
  selector:
    io.kompose.service: auth
status:
  loadBalancer: { }
