// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: gateway/gatewayProto/gateway.proto

package gatewayProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IntResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data int64 `protobuf:"varint,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *IntResponse) Reset() {
	*x = IntResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IntResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntResponse) ProtoMessage() {}

func (x *IntResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntResponse.ProtoReflect.Descriptor instead.
func (*IntResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gatewayProto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *IntResponse) GetData() int64 {
	if x != nil {
		return x.Data
	}
	return 0
}

type StringArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str string `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
}

func (x *StringArg) Reset() {
	*x = StringArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringArg) ProtoMessage() {}

func (x *StringArg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringArg.ProtoReflect.Descriptor instead.
func (*StringArg) Descriptor() ([]byte, []int) {
	return file_gateway_gatewayProto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *StringArg) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type IdArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *IdArg) Reset() {
	*x = IdArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdArg) ProtoMessage() {}

func (x *IdArg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdArg.ProtoReflect.Descriptor instead.
func (*IdArg) Descriptor() ([]byte, []int) {
	return file_gateway_gatewayProto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *IdArg) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserIdTrackIdArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TrackId int64 `protobuf:"varint,2,opt,name=trackId,proto3" json:"trackId,omitempty"`
}

func (x *UserIdTrackIdArg) Reset() {
	*x = UserIdTrackIdArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIdTrackIdArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdTrackIdArg) ProtoMessage() {}

func (x *UserIdTrackIdArg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdTrackIdArg.ProtoReflect.Descriptor instead.
func (*UserIdTrackIdArg) Descriptor() ([]byte, []int) {
	return file_gateway_gatewayProto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *UserIdTrackIdArg) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserIdTrackIdArg) GetTrackId() int64 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

type UserIdArtistIdArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ArtistId int64 `protobuf:"varint,2,opt,name=artistId,proto3" json:"artistId,omitempty"`
}

func (x *UserIdArtistIdArg) Reset() {
	*x = UserIdArtistIdArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIdArtistIdArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdArtistIdArg) ProtoMessage() {}

func (x *UserIdArtistIdArg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdArtistIdArg.ProtoReflect.Descriptor instead.
func (*UserIdArtistIdArg) Descriptor() ([]byte, []int) {
	return file_gateway_gatewayProto_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *UserIdArtistIdArg) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserIdArtistIdArg) GetArtistId() int64 {
	if x != nil {
		return x.ArtistId
	}
	return 0
}

type UserIdAlbumIdArg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AlbumId int64 `protobuf:"varint,2,opt,name=albumId,proto3" json:"albumId,omitempty"`
}

func (x *UserIdAlbumIdArg) Reset() {
	*x = UserIdAlbumIdArg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserIdAlbumIdArg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdAlbumIdArg) ProtoMessage() {}

func (x *UserIdAlbumIdArg) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdAlbumIdArg.ProtoReflect.Descriptor instead.
func (*UserIdAlbumIdArg) Descriptor() ([]byte, []int) {
	return file_gateway_gatewayProto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *UserIdAlbumIdArg) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserIdAlbumIdArg) GetAlbumId() int64 {
	if x != nil {
		return x.AlbumId
	}
	return 0
}

type LikeCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *LikeCheckResponse) Reset() {
	*x = LikeCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCheckResponse) ProtoMessage() {}

func (x *LikeCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gatewayProto_gateway_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCheckResponse.ProtoReflect.Descriptor instead.
func (*LikeCheckResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gatewayProto_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *LikeCheckResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_gateway_gatewayProto_gateway_proto protoreflect.FileDescriptor

var file_gateway_gatewayProto_gateway_proto_rawDesc = []byte{
	0x0a, 0x22, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22, 0x21, 0x0a,
	0x0b, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x1d, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x41, 0x72, 0x67, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x22,
	0x17, 0x0a, 0x05, 0x49, 0x64, 0x41, 0x72, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x41, 0x72, 0x67, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x22, 0x47,
	0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x64,
	0x41, 0x72, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61,
	0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x64, 0x41, 0x72, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x49, 0x64, 0x22, 0x23, 0x0a,
	0x11, 0x4c, 0x69, 0x6b, 0x65, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x42, 0x54, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x67, 0x6f, 0x2d, 0x70, 0x61, 0x72, 0x6b, 0x2d, 0x6d, 0x61, 0x69, 0x6c, 0x2d, 0x72, 0x75,
	0x2f, 0x32, 0x30, 0x32, 0x32, 0x5f, 0x31, 0x5f, 0x57, 0x61, 0x76, 0x65, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_gatewayProto_gateway_proto_rawDescOnce sync.Once
	file_gateway_gatewayProto_gateway_proto_rawDescData = file_gateway_gatewayProto_gateway_proto_rawDesc
)

func file_gateway_gatewayProto_gateway_proto_rawDescGZIP() []byte {
	file_gateway_gatewayProto_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_gatewayProto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_gatewayProto_gateway_proto_rawDescData)
	})
	return file_gateway_gatewayProto_gateway_proto_rawDescData
}

var file_gateway_gatewayProto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gateway_gatewayProto_gateway_proto_goTypes = []interface{}{
	(*IntResponse)(nil),       // 0: gateway.IntResponse
	(*StringArg)(nil),         // 1: gateway.StringArg
	(*IdArg)(nil),             // 2: gateway.IdArg
	(*UserIdTrackIdArg)(nil),  // 3: gateway.UserIdTrackIdArg
	(*UserIdArtistIdArg)(nil), // 4: gateway.UserIdArtistIdArg
	(*UserIdAlbumIdArg)(nil),  // 5: gateway.UserIdAlbumIdArg
	(*LikeCheckResponse)(nil), // 6: gateway.LikeCheckResponse
}
var file_gateway_gatewayProto_gateway_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_gatewayProto_gateway_proto_init() }
func file_gateway_gatewayProto_gateway_proto_init() {
	if File_gateway_gatewayProto_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_gatewayProto_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IntResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_gatewayProto_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_gatewayProto_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_gatewayProto_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIdTrackIdArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_gatewayProto_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIdArtistIdArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_gatewayProto_gateway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserIdAlbumIdArg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateway_gatewayProto_gateway_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_gatewayProto_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_gatewayProto_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_gatewayProto_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_gatewayProto_gateway_proto_msgTypes,
	}.Build()
	File_gateway_gatewayProto_gateway_proto = out.File
	file_gateway_gatewayProto_gateway_proto_rawDesc = nil
	file_gateway_gatewayProto_gateway_proto_goTypes = nil
	file_gateway_gatewayProto_gateway_proto_depIdxs = nil
}
