apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: wave
  name: wave
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wave
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: wave
    spec:
      containers:
        - name: api
          image: mausved/wave_api
          ports:
            - containerPort: 5000
          tty: true
          env:
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: secretkey
                  key: AWS_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: secretkey
                  key: ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: secretkey
                  key: SECRET_KEY
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: secretkey
                  key: AWS_BUCKET_NAME
            - name: AWS_S3_URL
              valueFrom:
                secretKeyRef:
                  name: secretkey
                  key: AWS_S3_URL
      restartPolicy: Always
      imagePullSecrets:
        - name: wave

status: { }
