apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: wave
  name: wave
spec:
  type: LoadBalancer
  ports:
    - name: "5000"
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: wave
    io.kompose.service: wave
