apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  ports:
    - name: "8095"
      port: 8095
      targetPort: 8095
  selector:
    io.kompose.service: nodejs
status:
  loadBalancer: { }
