apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nodejs
    spec:
      containers:
        - name: nodejs
          image: rius/wave.music.front
          ports:
            - containerPort: 8095
          env:
            - name: DATABASE_CONNECTION
              value: user=postgres password=music dbname=wave host=db port=5432 sslmode=disable
            - name: dbType
              value: postgres
      restartPolicy: Always
      imagePullSecrets:
        - name: wave

status: { }
