apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: linker
  name: linker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: linker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: linker
    spec:
      containers:
        - name: linker
          image: mausved/wave_linker
          ports:
            - containerPort: 8087
            - containerPort: 9087
          env:

            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secretmongo
                  key: MONGO_INITDB_ROOT_USERNAME

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secretmongo
                  key: MONGO_INITDB_ROOT_PASSWORD

            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: secretmongo
                  key: MONGO_INITDB_DATABASE

            - name: ME_CONFIG_MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: secretmongo
                  key: ME_CONFIG_MONGODB_URL

            - name: dbType
              valueFrom:
                secretKeyRef:
                  name: secretmongo
                  key: dbType

            - name: exporterPort
              value: :9087
            - name: port
              value: :8087
      restartPolicy: Always
      imagePullSecrets:
        - name: wave

status: { }
