// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/go-park-mail-ru/2022_1_Wave/internal/app/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// SessionRepo is an autogenerated mock type for the SessionRepo type
type SessionRepo struct {
	mock.Mock
}

// DeleteSession provides a mock function with given fields: sessionId
func (_m *SessionRepo) DeleteSession(sessionId string) error {
	ret := _m.Called(sessionId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sessionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetSession provides a mock function with given fields: sessionId
func (_m *SessionRepo) GetSession(sessionId string) (*domain.Session, error) {
	ret := _m.Called(sessionId)

	var r0 *domain.Session
	if rf, ok := ret.Get(0).(func(string) *domain.Session); ok {
		r0 = rf(sessionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sessionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSize provides a mock function with given fields:
func (_m *SessionRepo) GetSize() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeSessionAuthorized provides a mock function with given fields: sessionId, userId
func (_m *SessionRepo) MakeSessionAuthorized(sessionId string, userId uint) error {
	ret := _m.Called(sessionId, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, uint) error); ok {
		r0 = rf(sessionId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MakeSessionUnauthorized provides a mock function with given fields: sessionId
func (_m *SessionRepo) MakeSessionUnauthorized(sessionId string) error {
	ret := _m.Called(sessionId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sessionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetNewUnauthorizedSession provides a mock function with given fields: expires
func (_m *SessionRepo) SetNewUnauthorizedSession(expires time.Duration) (string, error) {
	ret := _m.Called(expires)

	var r0 string
	if rf, ok := ret.Get(0).(func(time.Duration) string); ok {
		r0 = rf(expires)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(time.Duration) error); ok {
		r1 = rf(expires)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
