// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/go-park-mail-ru/2022_1_Wave/internal/app/domain"
	mock "github.com/stretchr/testify/mock"
)

// TrackRepo is an autogenerated mock type for the TrackRepo type
type TrackRepo struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0
func (_m *TrackRepo) Delete(_a0 int) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *TrackRepo) GetAll() ([]domain.Track, error) {
	ret := _m.Called()

	var r0 []domain.Track
	if rf, ok := ret.Get(0).(func() []domain.Track); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLastId provides a mock function with given fields:
func (_m *TrackRepo) GetLastId() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPopular provides a mock function with given fields:
func (_m *TrackRepo) GetPopular() ([]domain.Track, error) {
	ret := _m.Called()

	var r0 []domain.Track
	if rf, ok := ret.Get(0).(func() []domain.Track); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPopularTracksFromArtist provides a mock function with given fields: artistId
func (_m *TrackRepo) GetPopularTracksFromArtist(artistId int) ([]domain.Track, error) {
	ret := _m.Called(artistId)

	var r0 []domain.Track
	if rf, ok := ret.Get(0).(func(int) []domain.Track); ok {
		r0 = rf(artistId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(artistId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSize provides a mock function with given fields:
func (_m *TrackRepo) GetSize() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTracksFromAlbum provides a mock function with given fields: albumId
func (_m *TrackRepo) GetTracksFromAlbum(albumId int) ([]domain.Track, error) {
	ret := _m.Called(albumId)

	var r0 []domain.Track
	if rf, ok := ret.Get(0).(func(int) []domain.Track); ok {
		r0 = rf(albumId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(albumId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0
func (_m *TrackRepo) Insert(_a0 domain.Track) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Track) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SelectByID provides a mock function with given fields: _a0
func (_m *TrackRepo) SelectByID(_a0 int) (*domain.Track, error) {
	ret := _m.Called(_a0)

	var r0 *domain.Track
	if rf, ok := ret.Get(0).(func(int) *domain.Track); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *TrackRepo) Update(_a0 domain.Track) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Track) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
