apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-exporter
  name: postgres-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-exporter
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-exporter
    spec:
      containers:
        - env:
            - name: ADMIN_PASSWORD
            - name: ADMIN_USER
            - name: DATA_SOURCE_NAME
              value: postgresql://postgres:music@db.default.svc.cluster.local:5432/wave?sslmode=disable
            - name: USER
              value: mai
          image: wrouesnel/postgres_exporter
          name: postgres-exporter
      restartPolicy: Always
      imagePullSecrets:
        - name: wave
status: { }
