apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-exporter
  name: postgres-exporter
spec:
  ports:
    - name: "9187"
      port: 9187
      targetPort: 9187
  selector:
    io.kompose.service: postgres-exporter
status:
  loadBalancer: { }
