apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: websocket
  name: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: websocket
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: websocket
    spec:
      containers:
        - name: websocket
          image: mausved/wave_websocket
          ports:
            - containerPort: 6789
          env:
            - name: REDIS_ADDR
              valueFrom:
                secretKeyRef:
                  name: secretredis
                  key: REDIS_ADDR
            - name: AUTH_GRPC_ADDR
              valueFrom:
                secretKeyRef:
                  name: secretredis
                  key: AUTH_GRPC_ADDR
            - name: dbType
              valueFrom:
                secretKeyRef:
                  name: secretredis
                  key: dbType
      imagePullSecrets:
        - name: wave

status: { }
